# backend/Dockerfile.dev
FROM node:22-alpine

# Install dependencies for Node native modules (important for Strapi/bcrypt/sharp)
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

EXPOSE 1337

CMD ["pnpm", "run", "develop"]